version: '3.8'

services:
  ai-service:
    image: resume-ai-service
    container_name: resume-ai-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
